### ISSUE TITLE
Big Issue NSNotificationCenter

### ISSUE THREAD

**Issue by vishaldeshai** [ArtSabintsev/UIFloatLabelTextView#12]
I have taken 2 textview and out of 2 i am editing 1 textview but its line color change like change text simulataneouly.

thanks in advance.

**Comment by ArtSabintsev** [comment]
I cannot replicate this problem in the sample project, which also has two text views. You may have setup something improperly. Please check the sample project for a guide on how to work with two test views on the same VC.

If you can provide me with a sample project that's easy to read, I can take a look. Feel free to reopen this issue if you would like more assistance.

**Comment by vishaldeshai** [comment]
Actually implementation  is not the problem but when we are editing textview the textviewDidBeginEditing calls for both the textview

And important thing is both the textviews are on one viewcontroller

If you takes delegates method then every delegate method calls seperately.

**Comment by vishaldeshai** [comment]
I am talking about textviewDidBeginEditing:(notificationcenter) method not general methods
I replaced notification method with delegate method and its works fine now.

**Comment by ArtSabintsev** [comment]
ok - great- happy it works! Have a good day!
