### ISSUE TITLE
Prevent Label from disappearing upon scrolling

### ISSUE THREAD

**Issue by chemjournal** [ArtSabintsev/UIFloatLabelTextView#8]
When the TextView is limited to a certain height, the label disappears when the user scrolls beyond the viewport of the TextView. How can this be disabled? Thanks

**Comment by ArtSabintsev** [comment]
I think it's functioning as intended, but I'll see if I can add this feature.

**Comment by chemjournal** [comment]
Awesome! Let me know how I can help.

**Comment by ArtSabintsev** [comment]
I thought about this feature. The point of the floating label is to remind the user the name/purpose of the field/view after they've filled it out, not while they're filling it out. Therefore, I will not be adding this feature. 

Sorry for taking so long to respond - I had to think about it for a bit.
