### ISSUE TITLE
placeholder text is being set as the .text

### ISSUE THREAD

**Issue by halpz** [ArtSabintsev/UIFloatLabelTextView#9]
when I try to get the text from an empty UIFloatLabelTextView, I get the placeholder value instead

**Comment by ArtSabintsev** [comment]
thanks for the heads-up. I'll take a look

**Comment by ArtSabintsev** [comment]
Ah, right, that's because to get this effect to work, I had to place the the placeholder in the textfield's text property when he test field was empty.

https://github.com/ArtSabintsev/UIFloatLabelTextView/blob/master/UIFloatLabelTextView/UIFloatLabelTextView.m#L208-L214
